from libretro.protocol import Proto
from libretro.crypto import random_buffer

"""\
A registration key is needed on account creating/registration.
It's a 32 byte unique random value generated by the server.
"""

class RegKey:

	def __init__(self, regkey:bytes=None):
		self.rkey = regkey

	def gen(self):
		self.rkey = random_buffer(Proto.REGKEY_SIZE)

	def read_string(self, regkey_string):
		if len(regkey_string) != 2*Proto.REGKEY_SIZE:
			raise ValueError("Invalid regkey string length")
		self.rkey = bytes.fromhex(regkey_string)

	def read_file(self, path):
		self.read_string(open(path, 'r').read(64))

	def write_file(self, path):
		with open(path, 'w') as f:
			f.write(self.hex())
	def bytes(self):
		return self.rkey

	def hex(self):
		return self.rkey.hex()

